#!/usr/bin/env node
/**
 * AI Portfolio Platform — Interactive Setup Wizard
 * Run: npm run setup
 */

const readline = require('readline')
const fs = require('fs')
const path = require('path')

const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
const ask = (q) => new Promise(resolve => rl.question(q, resolve))

const THEMES = ['cyberpunk-ai', 'terminal-hacker', 'glassmorphism', 'minimal-professional', 'futuristic-space', 'anime-gaming', 'retro-pixel']

const cyan = (s) => `\x1b[36m${s}\x1b[0m`
const green = (s) => `\x1b[32m${s}\x1b[0m`
const yellow = (s) => `\x1b[33m${s}\x1b[0m`
const bold = (s) => `\x1b[1m${s}\x1b[0m`

async function main() {
  console.clear()
  console.log(cyan(`
  ╔═══════════════════════════════════════════════╗
  ║   AI Portfolio Platform — Setup Wizard v1.0   ║
  ╚═══════════════════════════════════════════════╝
  `))
  console.log('This wizard will create your .env.local file.\n')
  console.log(yellow('Press Enter to use defaults (shown in brackets)\n'))

  const openaiKey = await ask(`${bold('OpenAI API Key')} (sk-...): `)
  const pineconeKey = await ask(`${bold('Pinecone API Key')}: `)
  const pineconeEnv = await ask(`${bold('Pinecone Region')} [us-east-1]: `) || 'us-east-1'
  const pineconeIndex = await ask(`${bold('Pinecone Index Name')} [portfolio]: `) || 'portfolio'
  const dashPass = await ask(`${bold('Dashboard Password')} (choose something secure): `)
  const portfolioUrl = await ask(`${bold('Your deployed URL')} [https://your-name.vercel.app]: `) || 'https://your-name.vercel.app'

  console.log(`\n${bold('Default Theme')} — choose a number:`)
  THEMES.forEach((t, i) => console.log(`  ${cyan(i + 1)}. ${t}`))
  const themeChoice = await ask('Theme [1]: ')
  const defaultTheme = THEMES[parseInt(themeChoice || '1') - 1] || 'cyberpunk-ai'

  const smtpUser = await ask(`\n${bold('Gmail address')} (for contact form, optional): `)
  const smtpPass = smtpUser ? await ask(`${bold('Gmail App Password')} (not your real password): `) : ''

  const gaId = await ask(`${bold('Google Analytics ID')} (G-..., optional): `)

  const envContent = `# Generated by npm run setup — ${new Date().toISOString()}
# DO NOT commit this file to git

# ---- OPENAI ----
OPENAI_API_KEY=${openaiKey}
OPENAI_MODEL=gpt-4-turbo-preview

# ---- PINECONE ----
PINECONE_API_KEY=${pineconeKey}
PINECONE_ENVIRONMENT=${pineconeEnv}
PINECONE_INDEX_NAME=${pineconeIndex}

# ---- DASHBOARD ----
DASHBOARD_PASSWORD=${dashPass}

# ---- PORTFOLIO ----
NEXT_PUBLIC_PORTFOLIO_NAME=Phaneendra Gavara
NEXT_PUBLIC_PORTFOLIO_EMAIL=phaneendragavara436@gmail.com
NEXT_PUBLIC_PORTFOLIO_URL=${portfolioUrl}
NEXT_PUBLIC_DEFAULT_THEME=${defaultTheme}

# ---- CONTACT FORM ----
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=${smtpUser}
SMTP_PASS=${smtpPass}
CONTACT_TO_EMAIL=${smtpUser || 'phaneendragavara436@gmail.com'}

# ---- ANALYTICS ----
NEXT_PUBLIC_GA_ID=${gaId}
`

  fs.writeFileSync(path.join(__dirname, '..', '.env.local'), envContent)

  console.log(`\n${green('✅  .env.local created successfully!')}`)
  console.log(`\n${bold('Next steps:')}`)
  console.log(`  1. ${cyan('npm install')}`)
  console.log(`  2. ${cyan('npm run dev')} — start local development`)
  console.log(`  3. Open ${cyan('http://localhost:3000')}`)
  console.log(`  4. Visit ${cyan('http://localhost:3000/dashboard')} to index your content`)
  console.log(`  5. Push to GitHub → connect to Vercel to deploy\n`)

  rl.close()
}

main().catch(err => { console.error(err); rl.close(); process.exit(1) })
